begin;

INSERT INTO zonas VALUES ('00', 'LUCENTUM CAMPUS');
INSERT INTO zonas VALUES ('01', 'TABARKA CAMPUS');
INSERT INTO zonas VALUES ('02', 'CITY CAMPUS');


INSERT INTO edificios VALUES ('00', '00', 'COMMONS AREAS / ZONAS COMUNES', 'Commons areas', true, 0.0000000000, 0.0000000000, true, false, false, false, false);
INSERT INTO edificios VALUES ('00', '01', 'RECTORY / RECTORADO', 'Rectory building', true, 0.0000000000, 0.0000000000, true, true, false, false, true);
INSERT INTO edificios VALUES ('00', '02', 'SERVICES BUILDING / SERVICIOS GENERALES', 'Services building', true, 0.0000000000, 0.0000000000, true, true, true, false, false);
INSERT INTO edificios VALUES ('01', '00', 'COMMONS AREAS / ZONAS COMUNES', 'Commons areas', true, 0.0000000000, 0.0000000000, true, false, false, false, false);
INSERT INTO edificios VALUES ('01', '01', 'SCIENCES FACULTY / FACULTAD DE CIENCIAS', 'Sciences Faculty', true, 0.0000000000, 0.0000000000, true, true, false, false, false);
INSERT INTO edificios VALUES ('01', '02', 'MAIN HALL /SALÓN DE ACTOS', 'Main Hall', true, 0.0000000000, 0.0000000000, true, false, false, false, false);
INSERT INTO edificios VALUES ('02', '01', 'ENGINEERING SCHOOL / ESCUELA DE INGENIERÍA', 'Engineering School', true, 0.0000000000, 0.0000000000, true, true, true, true, false);


INSERT INTO centros VALUES ('17.01', 'RECTORADO Y SERVICIOS GENERALES');
INSERT INTO centros VALUES ('1B00', 'SIN ASIGNAR');
INSERT INTO centros VALUES ('1B01', 'FACULTAD CIENCIAS');
INSERT INTO centros VALUES ('1B03', 'FACULTAD DERECHO');
INSERT INTO centros VALUES ('1B04', 'FACULTAD FILOSOFIA Y LETRAS');
INSERT INTO centros VALUES ('1B13', 'ESCUELA POLITECNICA SUPERIOR');
INSERT INTO centros VALUES ('1B14', 'FACULTAD EDUCACION');
INSERT INTO centros VALUES ('1B02', 'FACULTAD CC ECONOMICAS Y EMPRESARIALE');
INSERT INTO centros VALUES ('1B15', 'FACULTAD CIENCIAS DE LA SALUD');
INSERT INTO centros VALUES ('02.10', 'VICERRECTORADO INVEST., DESAR. E INNOV.');


INSERT INTO actividades VALUES (200, 'Mobiliario urbano', 'Mobiliario', 'Mobiliari urbà', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (202, 'Papelera', 'Mobiliario', 'Paperera', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (203, 'Contenedor', 'Mobiliario', 'Contenidor', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (204, 'Señal indicativa', 'Mobiliario', 'Senyal indicatiu', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (206, 'Trapas de alcantarillado', 'Mobiliario', 'Trapes de clavegueram', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (210, 'Bandera', 'Mobiliario', 'Bandera', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (211, 'Cámara Webcam', 'Mobiliario', 'Càmera Webcam', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (212, 'Placa conmemorativa', 'Mobiliario', 'Placa commemorativa', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (400, 'Puerta acceso principal', 'Varios', 'Puerta accés principal ', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (401, 'Puertas acceso secundarias ', 'Varios', 'Portes accés secundàries', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (402, 'Puertas acceso secundarias con llave', 'Varios', 'Portes accés secundàries amb clau', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (93, 'Muros', 'Muros', 'Murs', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (91, 'Accesos exteriores a edificios', 'Accesos', 'Accessos exteriors a edificis', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (209, 'Cabina Telefonos', 'Mobiliario', 'Cabina Telèfons ', false, 'OTROS SERVICIOS', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (79, 'Armario', 'Varios', 'Armari', true, 'COLEGIO MAYOR', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (0, 'No ocupada', 'Varios', 'No ocupada', true, 'NO OCUPADA / OBRAS', '--', true, true, false,  NULL);
INSERT INTO actividades VALUES (116, 'Señalización viarios', 'Comunes', 'Senyalizacio viaris', false, 'ESPACIOS COMUNES', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (207, 'Marquesinas', 'Mobiliario', 'Marquesines', false, 'ESPACIOS COMUNES', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (208, 'Banco', 'Mobiliario', 'Banc', false, 'ESPACIOS COMUNES', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (11, 'Almacén', 'Varios', 'Magatzem', true, 'GESTIÓN Y ADMINISTRACIÓN', '--', true, true, true,  NULL);
INSERT INTO actividades VALUES (2, 'Aula de informática', 'Docencia', 'Aula d''informàtica ', true, 'DOCENCIA', 'INFORM', false, true, true, 'AULAS INFORMATICA');
INSERT INTO actividades VALUES (50, 'Obras', 'Varios', 'Obres', true, 'NO OCUPADA / OBRAS', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (78, 'Dormitorio', 'Varios', 'Dormitori', true, 'COLEGIO MAYOR', '--', true, true, true,  NULL);
INSERT INTO actividades VALUES (5, 'Laboratorio de investigación/docencia', 'Laboratorio', 'Laboratori d''investigació/docència', true, 'DOCENCIA', 'LABDOC', true, true, true,  NULL);
INSERT INTO actividades VALUES (17, 'Reprografía', 'Varios', 'Copistería', true, 'OTROS SERVICIOS', '--', true, true, true, NULL);
INSERT INTO actividades VALUES (19, 'Cafetería', 'Varios', 'Cafeteria', true, 'OTROS SERVICIOS', '--', true, true, true,  NULL);
INSERT INTO actividades VALUES (21, 'Comercial', 'Varios', 'Comercial', true, 'OTROS SERVICIOS', '--', true, true, true,  NULL);
INSERT INTO actividades VALUES (301, 'Árboles', 'Vegetación', 'Arbres', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (99, 'Varios', 'Varios', 'Diversos', true, 'OTROS SERVICIOS', '--', true, true, true,  NULL);
INSERT INTO actividades VALUES (120, 'Base edificios', 'Comunes', 'Base edificis', false, '--', '--', false, false, true,  NULL);
INSERT INTO actividades VALUES (4, 'Laboratorio de investigación', 'Laboratorio', 'Laboratori d''investigació', true, 'INVESTIGACIÓN', 'LABINV', true, true, true,  NULL);
INSERT INTO actividades VALUES (7, 'Despacho', 'Despacho', 'Despatx', true, 'DESPACHOS Y SEMINARIOS', 'DESP', true, true, true,  'DESPACHOS');
INSERT INTO actividades VALUES (8, 'Administración', 'Administración', 'Administració', true, 'GESTIÓN Y ADMINISTRACIÓN', '--', true, true, true,  'DESPACHOS');
INSERT INTO actividades VALUES (9, 'Biblioteca', 'Biblioteca', 'Biblioteca', true, 'BIBLIOTECA, HEMEROTECA Y ARCHIVOS', 'BIBLIO', true, true, true,  'BIBLIOTECAS');
INSERT INTO actividades VALUES (12, 'Sala de reuniones', 'Salas', 'Sala de reunions', true, 'GESTIÓN Y ADMINISTRACIÓN', 'SALA', true, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (13, 'Sala de audiovisuales', 'Salas', 'Sala d''audiovisuals', true, 'INSTALACIONES CULTURALES', 'AUDIOV', true, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (15, 'Seminario', 'Docencia', 'Seminari', true, 'DESPACHOS Y SEMINARIOS', 'SEM', true, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (16, 'Conserjería', 'Conserjería', 'Consergeria', true, 'OTROS SERVICIOS', '--', true, true, true,  'CONSERJERIAS');
INSERT INTO actividades VALUES (18, 'Mantenimiento', 'Varios', 'Manteniment', true, 'ESPACIOS COMUNES', '--', false, true, true,  'INSTALACIONES');
INSERT INTO actividades VALUES (94, 'Ascensor', 'Accesos', 'Ascensor', true, 'ESPACIOS COMUNES', '--', false, true, true,  'INSTALACIONES');
INSERT INTO actividades VALUES (26, 'Aula de dibujo', 'Docencia', 'Aula dibuix', true, 'DOCENCIA', 'DIBUJO', false, true, true,  'AULAS OTRAS');
INSERT INTO actividades VALUES (80, 'Escaleras de emergencia', 'Accesos', 'Escales d''emergència', true, 'ESPACIOS COMUNES', '--', false, true, false,  'ESPACIOS COMUNES INTERIORES');
INSERT INTO actividades VALUES (81, 'Puertas de emergencia', 'Accesos', 'Portes d''emergència', false, '--', '--', false, true, false,  'ESPACIOS COMUNES INTERIORES');
INSERT INTO actividades VALUES (95, 'Terrazas', 'Accesos', 'Terrasses', false, 'ESPACIOS COMUNES', '--', false, true, true,  'AZOTEAS');
INSERT INTO actividades VALUES (96, 'Escaleras', 'Accesos', 'Escales', true, 'ESPACIOS COMUNES', '--', false, true, false,  'ESPACIOS COMUNES INTERIORES');
INSERT INTO actividades VALUES (97, 'Vestíbulos', 'Accesos', 'Vestíbuls', true, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES INTERIORES');
INSERT INTO actividades VALUES (101, 'Jardines', 'Comunes', 'Jardins', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (102, 'Accesos al campus', 'Comunes', 'Accessos al campus', false, 'ESPACIOS COMUNES', '--', false, true, false,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (103, 'Zona peatonal', 'Comunes', 'Zona peatonal', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (104, 'Viales', 'Comunes', 'Viaris', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (106, 'Pasos de cebra', 'Comunes', 'Passos de zebra', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (107, 'Gradas', 'Comunes', 'Grades', false, 'INSTALACIONES DEPORTIVAS', '--', false, true, false,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (108, 'Monumentos', 'Comunes', 'Monuments', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (110, 'Aparcamiento Discapacitados', 'Comunes', 'Aparcament discapacitats', false, 'APARCAMIENTOS', '--', false, true, true, 'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (111, 'Aparcamiento Bus', 'Comunes', 'Aparcament bus', false, 'APARCAMIENTOS', '--', false, true, true, 'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (113, 'Aparcamiento Motocicleta', 'Comunes', 'Aparcament motocicleta', false, 'APARCAMIENTOS', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (115, 'Caminos', 'Comunes', 'Camins', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (121, 'Anfiteatro', 'Comunes', 'Anfiteatre', false, 'INSTALACIONES CULTURALES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (122, 'Patios interiores', 'Comunes', 'Patis', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (20, 'Aseos', 'Aseos', 'Lavabos', true, 'ESPACIOS COMUNES', '--', false, true, false,  'ASEOS');
INSERT INTO actividades VALUES (24, 'Instalaciones deportivas interiores', 'Varios', 'Instalació esportiva interior', true, 'INSTALACIONES DEPORTIVAS', 'DEPORTE', false, true, true,  'INSTALACIONES DEPORTIVAS INTERIORES');
INSERT INTO actividades VALUES (92, 'Rampas', 'Accesos', 'Rampes', false, 'ESPACIOS COMUNES', '--', false, true, false,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (205, 'Hidrante', 'Mobiliario', 'Hidrante', false, 'ESPACIOS COMUNES', '--', false, true, false,  'INSTALACIONES');
INSERT INTO actividades VALUES (201, 'Farola', 'Mobiliario', 'Fanal', false, 'ESPACIOS COMUNES', '--', false, true, false,  'INSTALACIONES');
INSERT INTO actividades VALUES (123, 'Paneles solares', 'Varios', 'Panels solars', false, 'INVESTIGACIÓN', '--', false, true, true,  'INSTALACIONES');
INSERT INTO actividades VALUES (114, 'Fuente', 'Comunes', 'Font', false, 'ESPACIOS COMUNES', '--', false, true, false,  'INSTALACIONES');
INSERT INTO actividades VALUES (305, 'Invernadero', 'Varios', 'hivernàcul', false, 'INVESTIGACIÓN', '--', false, true, true,  'LABORATORIO BIOLOGICO');
INSERT INTO actividades VALUES (302, 'Arbustos', 'Vegetación', 'Arbustos', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (303, 'Herbáceos', 'Vegetación', 'Herbacis', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (304, 'Maceteros', 'Vegetación', 'Maceteros', false, 'ESPACIOS COMUNES', '--', false, true, false,  NULL);
INSERT INTO actividades VALUES (300, 'Vegetación', 'Vegetación', 'Vegetació', false, 'ESPACIOS COMUNES', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (306, 'Planta solar', 'Varios', 'Planta solar', false, 'ESPACIOS COMUNES', '--', false, true, true,  NULL);
INSERT INTO actividades VALUES (1, 'Aula de teoría', 'Docencia', 'Aula de teoria', true, 'DOCENCIA', 'AULA', false, true, true,  'AULAS CONVENCIONALES');
INSERT INTO actividades VALUES (3, 'Aula experimental', 'Docencia', 'Aula experimental', true, 'DOCENCIA', 'AULEX', false, true, true,  'AULAS OTRAS');
INSERT INTO actividades VALUES (6, 'Sala informática de libre acceso', 'Informática', 'Sala informàtica de lliure accés', true, 'BIBLIOTECA, HEMEROTECA Y ARCHIVOS', 'INFLIBRE', true, true, true,  'AULAS INFORMATICA');
INSERT INTO actividades VALUES (14, 'Salón de actos', 'Salas', 'Saló d''actes', true, 'INSTALACIONES CULTURALES', 'SALON', false, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (22, 'Sala informática de usuarios', 'Informática', 'Sala informàtica d''usuaris', true, 'BIBLIOTECA, HEMEROTECA Y ARCHIVOS', '--', true, true, true, 'AULAS INFORMATICA');
INSERT INTO actividades VALUES (23, 'Vestuarios', 'Varios', 'Vestidors', true, 'OTROS SERVICIOS', '--', false, true, true,  'VESTUARIOS');
INSERT INTO actividades VALUES (27, 'Sala multiusos', 'Salas', 'SALA MULTIUSOS', true, 'INSTALACIONES CULTURALES', 'SMUSOS', true, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (28, 'Sala de exposiciones', 'Salas', 'Sala d''exposicions', true, 'INSTALACIONES CULTURALES', 'SALON', false, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (29, 'Sala de videoconferencia', 'Salas', 'Sala videoconfèrencia', true, 'INSTALACIONES CULTURALES', 'VIDCONF', true, true, true,  'SALONES DE ACTOS');
INSERT INTO actividades VALUES (31, 'Talleres', 'Varios', 'Tallers', true, 'OTROS SERVICIOS', '--', true, true, true,  'TALLERES');
INSERT INTO actividades VALUES (98, 'Pasillos', 'Accesos', 'Corredors', true, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES INTERIORES');
INSERT INTO actividades VALUES (100, 'Espacios comunes del campus', 'Comunes', 'Espais comuns del campus', false, 'ESPACIOS COMUNES', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (109, 'Aparcamiento', 'Comunes', 'Aparcament', false, 'APARCAMIENTOS', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (112, 'Aparcamiento Bicicleta', 'Comunes', 'Aparcament bicicleta', false, 'APARCAMIENTOS', '--', false, true, true,  'ESPACIOS COMUNES EXTERIORES');
INSERT INTO actividades VALUES (30, 'Laboratorio de Docencia', 'Docencia', 'Laboratori de docència', true, 'DOCENCIA', 'LABDOC', true, true, true,  NULL);
INSERT INTO actividades VALUES (32, 'Comedor', 'Varios', 'Menjador', true, 'OTROS SERVICIOS', '--', false, true, true,  'COMEDOR');
INSERT INTO actividades VALUES (25, 'Instalaciones deportivas exteriores', 'Varios', 'Instalació esportiva exterior', true, 'INSTALACIONES DEPORTIVAS', 'DEPORTE', false, true, true,  'INSTALACIONES DEPORTIVAS EXTERIORES');
INSERT INTO actividades VALUES (105, 'Estanques y lagos', 'Comunes', 'Estanys i llacs ', false, 'ESPACIOS COMUNES', '--', false, true, true,  'INSTALACIONES');
INSERT INTO actividades VALUES (10, 'Archivo', 'Administración', 'Arxiu', true, 'BIBLIOTECA, HEMEROTECA Y ARCHIVOS', '--', true, true, true,  'ALMACENES OTROS');



INSERT INTO unidades VALUES ('07.08', 'SERVICIO SELECCION Y FORMACION', '1B00');
INSERT INTO unidades VALUES ('07.05', 'SERVICIO GESTION ACADEMICA', '1B00');
INSERT INTO unidades VALUES ('07.17', 'SERVICIO REGISTRO Y ARCHIVO', '1B00');
INSERT INTO unidades VALUES ('07.03', 'SERVICIO CONTABILIDAD', '1B00');
INSERT INTO unidades VALUES ('02.25', 'VICERRECTORADO REL. INSTITUCIONALES', '1B00');
INSERT INTO unidades VALUES ('X005', 'VIAJES HISPANIA', '1B00');
INSERT INTO unidades VALUES ('00.00', 'SIN DESTINO', '1B00');
INSERT INTO unidades VALUES ('02.31', 'OFICINA DE COOPERACION Y RELACIONES INT.', '1B00');
INSERT INTO unidades VALUES ('09.04', 'SECRETARIADO SOCRATES-EUROPA', '1B00');
INSERT INTO unidades VALUES ('02.21', 'SECRETARIADO EXTENSION UNIVERSITARIA', '1B00');
INSERT INTO unidades VALUES ('02.50', 'VICERRECTORADO TECN. E INNOVACION EDUC.', '1B00');
INSERT INTO unidades VALUES ('02.22', 'SECRETARIADO CULTURA', '1B00');
INSERT INTO unidades VALUES ('02.20', 'VICERRECTORADO EXTENSION UNIVERSITARI', '1B00');
INSERT INTO unidades VALUES ('02.00', 'VICERRECTORADO ORDENACION ACADEMICA Y', '1B00');
INSERT INTO unidades VALUES ('05.01', 'GERENCIA', '1B00');
INSERT INTO unidades VALUES ('205.02', 'SERVICIO CONTABILIDAD Y PRESUPUESTOS', '1B00');
INSERT INTO unidades VALUES ('07.07', 'SERVICIO CONTROL DE GESTION', '1B00');
INSERT INTO unidades VALUES ('07.02', 'SERVICIO GESTION DE PERSONAL', '1B00');
INSERT INTO unidades VALUES ('07.04', 'SERVICIO GESTION ECONOMICA', '1B00');
INSERT INTO unidades VALUES ('02.65', 'VICERRECTORADO DE INFRAEST. ESPAC. Y MED', '1B00');
INSERT INTO unidades VALUES ('07.10', 'SERVICIO JURIDICO', '1B00');
INSERT INTO unidades VALUES ('00.01', 'CONSEJO SOCIAL', '1B00');
INSERT INTO unidades VALUES ('09.24', 'UNIVERSIDAD PERMANENTE', '1B00');
INSERT INTO unidades VALUES ('07.018', 'GESTIÓN DE ESPACIOS', '1B00');
INSERT INTO unidades VALUES ('1B14', 'FACULTAD EDUCACION', '1B14');
INSERT INTO unidades VALUES ('07.13', 'SERVICIO GEST. INVEST. Y TRANSFERENCIA D', '1B00');
INSERT INTO unidades VALUES ('X011', 'CENTRO SUPERIOR DE IDIOMAS', '1B00');
INSERT INTO unidades VALUES ('06.01', 'AREA DE RECURSOS HUMANOS', '1B00');
INSERT INTO unidades VALUES ('01.20', 'AREA DE RECTORADO', NULL);
INSERT INTO unidades VALUES ('01.21', 'UNIDAD DE COMUNICACION', NULL);
INSERT INTO unidades VALUES ('02.10', 'VICERRECTORADO INVEST., DESAR. E INNOV.', '1B00');



INSERT INTO puestos VALUES ('A0505', 'Catedratico de escuela universitaria', 'PDI', true, 11);
INSERT INTO puestos VALUES ('A0500', 'Catedratico de universidad', 'PDI', true, 11);
INSERT INTO puestos VALUES ('A0504', 'Profesor titular universidad', 'PDI', true, 11);
INSERT INTO puestos VALUES ('A0506', 'Profesor titular escuela universitaria', 'PDI', true, 11);
INSERT INTO puestos VALUES ('00063', 'PROFESOR CONTRATADO DOCTOR (LOU)', 'PDI', true, 11);
INSERT INTO puestos VALUES ('7105', 'E. ADMINISTRATIVA DE LA UNIV. DE SEVILLA', 'PAS', false, 6);
INSERT INTO puestos VALUES ('7521', 'E. ADMINISTRATIVA DE LA UNIV. DE ALMERIA', 'PAS', false, 6);
INSERT INTO puestos VALUES ('00061', 'PROFESOR AYUDANTE DOCTOR (LOU)', 'PDI', false, 11);
INSERT INTO puestos VALUES ('00064', 'PROFESOR ASOCIADO (LOU)', 'PDI', false, 4);
INSERT INTO puestos VALUES ('00060', 'AYUDANTE (LOU)', 'PDI', false, 11);
INSERT INTO puestos VALUES ('00062', 'PROFESOR COLABORADOR (LOU)', 'PDI', false, 8);
INSERT INTO puestos VALUES ('N1448', 'Profesor asociado', 'PDI', false, 4);
INSERT INTO puestos VALUES ('7138', 'E. OFICIAL-ESPECIALISTA DE LA UNIV. DE A', 'PAS', false, 6);
INSERT INTO puestos VALUES ('7189', 'E. CONSERJE', 'PAS', false, 6);
INSERT INTO puestos VALUES ('50004', 'BEDEL', 'PAS', false, 6);
INSERT INTO puestos VALUES ('SP011', 'BECARIO', 'PDI', false, 6);
INSERT INTO puestos VALUES ('6000', 'E. TECNICA DE GESTION DE OOAA', 'PAS', false, 8);
INSERT INTO puestos VALUES ('6025', 'E. ADMINISTRATIVA DE OOAA', 'PAS', false, 8);
INSERT INTO puestos VALUES ('7000', 'E. TECNICA DE LA UNIVERSIDAD DE ALICANT', 'PAS', false, 8);
INSERT INTO puestos VALUES ('7002', 'E. GESTION DE LA  UNIV. DE ALICANTE', 'PAS', false, 8);
INSERT INTO puestos VALUES ('7004', 'E. ADMINISTRATIVA DE LA UNIV. DE ALICANT', 'PAS', false, 8);
INSERT INTO puestos VALUES ('7006', 'E. AUXILIAR DE LA UNIV. DE ALICANTE', 'PAS', false, 6);
INSERT INTO puestos VALUES ('10015', 'TECNICO SUPERIOR', 'PAS', false, 11);
INSERT INTO puestos VALUES ('10016A', 'TECNICO GRUPO A', 'PAS', false, 11);
INSERT INTO puestos VALUES ('10016B', 'TECNICO GRUPO B', 'PAS', false, 8);
INSERT INTO puestos VALUES ('O0', 'GRUPO A DE LA GENERALITAT VALENCIANA', 'PAS', false, 8);
INSERT INTO puestos VALUES ('10024', 'GESTOR', 'PAS', false, 6);
INSERT INTO puestos VALUES ('1111', 'CUERPO GEN TECNICO DE LA ADMIN. CIVIL ES', 'PAS', false, 8);
INSERT INTO puestos VALUES ('0015', 'C. TECNICO DE AUDITORIA Y CONTABILIDAD', 'PAS', false, 8);
INSERT INTO puestos VALUES ('CARGO', 'CARGO', 'OTROS', false, 11);
INSERT INTO puestos VALUES ('TÉCNICO', 'TÉCNICOS EXTERNOS', 'OTROS', false, 8);
INSERT INTO puestos VALUES ('ADMINISTRA', 'ADMINISTRATIVO EXTERNO', 'OTROS', false, 6);
INSERT INTO puestos VALUES ('DOCENTE', 'DOCENTE EXTERNO', 'OTROS', false, 8);
INSERT INTO puestos VALUES ('DIRECCIÓN', 'DIRECCION UNIDAD EXTERNA', 'OTROS', false, 11);
INSERT INTO puestos VALUES ('7008', 'E. BASICA DE CONSERJERIA Y APOYO', 'PAS', false, 6);




INSERT INTO cargos VALUES ('DSE67', 'DSC INNOVACION TECNOLOGICO-EDUCATIVA');
INSERT INTO cargos VALUES ('VDCEDU10', 'VFA INVESTIGACION Y POSGRADO');
INSERT INTO cargos VALUES ('VDCEDU11', 'VFA ESTUDIANTES Y EXTENSION CULTURAL');
INSERT INTO cargos VALUES ('VDCEDU12', 'VFA COORDINACION CURRICULAR');
INSERT INTO cargos VALUES ('DSE55', 'DSC INFORMATICA');
INSERT INTO cargos VALUES ('DD064', 'DDE INNOVACION Y FORMACION DIDACTICA');
INSERT INTO cargos VALUES ('DEC06', 'DECANO FACULTAD DE EDUCACION');
INSERT INTO cargos VALUES ('VDCEDU8', 'VFA PRACTICAS Y NORMALIZACION LINGUIST.');
INSERT INTO cargos VALUES ('VREC19', 'VIC RELACIONES INTERNACIONALES Y COOPERA');
INSERT INTO cargos VALUES ('VREC22', 'VIC INFRAESTRUCTURAS, ESP. Y MEDIO AMB.');
INSERT INTO cargos VALUES ('DSE60', 'DSC INVESTIGACION');
INSERT INTO cargos VALUES ('DSE62', 'DSC INTERNACIONALIZACION Y TRANSFERENCIA DE TECNOLOGIA');
INSERT INTO cargos VALUES ('DSE65', 'DSC PREVENCION Y SERVICIOS EXTERNALIZADOS');
INSERT INTO cargos VALUES ('VREC18', 'VIC TECNOLOGIA E INNOVACION EDUCATIVA');
INSERT INTO cargos VALUES ('VREC15', 'VIC INVESTIGACION, DESARROLLO E INNOVACI');
INSERT INTO cargos VALUES ('VREC16', 'VIC PLANIFICACION ECONOMICA');
INSERT INTO cargos VALUES ('VDCEDU1', 'VICEDECANO DE ORDENACION ACADEMICA');
INSERT INTO cargos VALUES ('CAC08', 'CAC UNIVERSIDAD PERMANENTE');
INSERT INTO cargos VALUES ('DSE41', 'DSC REL. INSTITUCIONALES Y CONVENIOS');
INSERT INTO cargos VALUES ('SFA06', 'SECRETARIO DE FAC. DE EDUCACION');
INSERT INTO cargos VALUES ('SRGEN', 'SECRETARIO GENERAL');
INSERT INTO cargos VALUES ('RECTOR', 'RECTOR');



INSERT INTO departamentos VALUES ('B156', 'CIENCIAS DE LA TIERRA Y DEL MEDIO AMBIE.', 'CTMA', 'Ciències de la Terra i del Medi Ambient', '1B01');
INSERT INTO departamentos VALUES ('B169', 'QUIMICA ANALITICA, NUTRICION Y BROMATOLO', 'QANA', 'Química Analítica, Nutrició i Bromatologia', '1B01');
INSERT INTO departamentos VALUES ('B176', 'SOCIOLOGIA II', NULL, NULL, '1B02');
INSERT INTO departamentos VALUES ('B142', 'FILOLOGIA CATALANA', 'FC', 'Filologia Catalana', '1B04');
INSERT INTO departamentos VALUES ('B115', 'FILOLOGIA ESPAÑOLA, LINGUISTICA GENERAL', 'FE', 'Filologia Espanyola, Lingüística General i Teoria de la Literatura', '1B04');
INSERT INTO departamentos VALUES ('B114', 'FILOLOGIAS INTEGRADAS', 'FINT', 'Filologies Integrades', '1B04');
INSERT INTO departamentos VALUES ('B112', 'DIDACTICA GENERAL Y DIDACTICAS ESPECIFIC', 'DGDE', 'Didàctica General i Didàctiques Específiques', '1B14');
INSERT INTO departamentos VALUES ('B166', 'INNOVACION Y FORMACION DIDACTICA', 'IFD', 'Innovació i Formació Didàctica', '1B14');
INSERT INTO departamentos VALUES ('B177', 'PSICOLOGIA EVOLUTIVA Y DIDACTICA', NULL, NULL, '1B14');
INSERT INTO departamentos VALUES ('07.13', 'SERVICIO GEST. INVEST. Y TRANSFERENCIA D', NULL, NULL, '1B00');
INSERT INTO departamentos VALUES ('B179', 'SOCIOLOGIA I', NULL, NULL, '1B14');


INSERT INTO subunidades VALUES ('05011000', 'SEC. ADM. GERENCIA');
INSERT INTO subunidades VALUES ('03010001', 'SEC. ADM. SECRETARIA GENERAL');
INSERT INTO subunidades VALUES ('00011003', 'SEC. ADM. CONSEJO SOCIAL');
INSERT INTO subunidades VALUES ('01210001', 'ADMINISTRACION OFICINA DE COMUNICACION');
INSERT INTO subunidades VALUES ('05011001', 'GERENCIA');
INSERT INTO subunidades VALUES ('01210002', 'RELACIONES CON LOS MEDIOS');
INSERT INTO subunidades VALUES ('02000001', 'SEC. ADM. VICERR. ORDENACION ACADEMICA');
INSERT INTO subunidades VALUES ('07051200', 'SUBDIRECCION DE ESPACIOS DOCENTES');
INSERT INTO subunidades VALUES ('07101110', 'SERVICIO JURIDICO');
INSERT INTO subunidades VALUES ('02200001', 'SEC. ADM. VICERR. EXTENSION UNIVERSITARI');
INSERT INTO subunidades VALUES ('02150001', 'SEC. ADM. VICERR.PLANIFICACION ECONOMICA');
INSERT INTO subunidades VALUES ('07041301', 'PATRIMONIO E INVENTARIO');
INSERT INTO subunidades VALUES ('02210100', 'SEDE CIUDAD DE ALICANTE');
INSERT INTO subunidades VALUES ('07021202', 'ACCION SOCIAL');
INSERT INTO subunidades VALUES ('02100001', 'SEC. ADM. VICERR.INVEST., DESAR. E INNOV');
INSERT INTO subunidades VALUES ('09310001', 'SEC. ADM. BIBL. VIRTUAL DE LENGUAS HISPA');
INSERT INTO subunidades VALUES ('02200300', 'UNIVERSIDAD PERMANENTE');
INSERT INTO subunidades VALUES ('01210003', 'CONSULTORIA INTERNA');
INSERT INTO subunidades VALUES ('1B140200', 'SEC. ADM. DPTO. INNOVACION Y FORMACION D');
INSERT INTO subunidades VALUES ('07041000', 'DIRECCION SERVICIO GESTION ECONOMICA');
INSERT INTO subunidades VALUES ('07081000', 'DIRECCION SERVICIO SELECCION Y FORMACION');
INSERT INTO subunidades VALUES ('01210004', 'COMUNICACION INTERNA Y WEB INSTITUCIONAL');
INSERT INTO subunidades VALUES ('1B140001', 'SEC. ADM. FACULTAD DE EDUCACION');
INSERT INTO subunidades VALUES ('1B140100', 'SEC. ADM. DPTO. DIDACTICA GENERAL Y DIDA');
INSERT INTO subunidades VALUES ('07051102', 'COORDINACION ACADEMICA');
INSERT INTO subunidades VALUES ('07021200', 'SUBDIRECCION NOMINAS Y ACCION SOCIAL');
INSERT INTO subunidades VALUES ('01210005', 'COMUNICACION ACADEMICA Y CIENTIFICA');
INSERT INTO subunidades VALUES ('07081101', 'ACCESO PDI');
INSERT INTO subunidades VALUES ('07051000', 'DIRECCION SERVICIO GESTION ACADEMICA');
INSERT INTO subunidades VALUES ('07051210', 'APOYO A LA DOCENCIA');
INSERT INTO subunidades VALUES ('1B140002', 'CONSERJERIA FACULTAD EDUCACION');
INSERT INTO subunidades VALUES ('07021201', 'NOMINAS');
INSERT INTO subunidades VALUES ('07021203', 'SEGURIDAD SOCIAL');
INSERT INTO subunidades VALUES ('07031100', 'SUBDIRECCION CONTABILIDAD');
INSERT INTO subunidades VALUES ('07031200', 'SUBDIRECCION TESORERIA');
INSERT INTO subunidades VALUES ('07081100', 'SUBDIRECCION SELECCION Y PROVISION');
INSERT INTO subunidades VALUES ('07051100', 'SUBDIRECCION COORDINACION ACAD. Y EST.');
INSERT INTO subunidades VALUES ('07041103', 'DIETAS');
INSERT INTO subunidades VALUES ('07041202', 'COMPRAS');
INSERT INTO subunidades VALUES ('07031102', 'FACTURACION');
INSERT INTO subunidades VALUES ('07051101', 'PLANES DE ESTUDIOS');
INSERT INTO subunidades VALUES ('01210006', 'PROYECCION');
INSERT INTO subunidades VALUES ('07051103', 'NORMATIVAS Y PLANIFICACION');
INSERT INTO subunidades VALUES ('07041201', 'CONTRATACION');
INSERT INTO subunidades VALUES ('07031101', 'CONTABILIDAD');
INSERT INTO subunidades VALUES ('07081102', 'SELECCION Y PROVISION PAS');
INSERT INTO subunidades VALUES ('07101101', 'ADMINISTRACION (SERVICIO JURIDICO)');
INSERT INTO subunidades VALUES ('07041102', 'CAJA');
INSERT INTO subunidades VALUES ('07041200', 'SUBDIRECCION CONTRATACION');
INSERT INTO subunidades VALUES ('07031000', 'DIRECCION SERVICIO CONTABILIDAD');
INSERT INTO subunidades VALUES ('07101000', 'DIRECCION SERVICIO JURIDICO');
INSERT INTO subunidades VALUES ('07171111', 'REGISTRO');
INSERT INTO subunidades VALUES ('1B140000', 'ADMINISTRACION FACULTAD DE EDUCACION');
INSERT INTO subunidades VALUES ('07171110', 'SUBDIRECCION REGISTRO');
INSERT INTO subunidades VALUES ('06011005', 'CONSERJERIA RECTORADO');
INSERT INTO subunidades VALUES ('07101100', 'DIRECCION ADJUNTA SERVICIO JURIDICO');
INSERT INTO subunidades VALUES ('07021101', 'GESTION P.D.I.');
INSERT INTO subunidades VALUES ('07021102', 'GESTION P.A.S.');
INSERT INTO subunidades VALUES ('07041101', 'VALIDACION');
INSERT INTO subunidades VALUES ('07041100', 'SUBDIRECCION GESTION ECONOMICA');
INSERT INTO subunidades VALUES ('07041300', 'SUBDIRECCION PATRIMONIO E INVENTARIO');
INSERT INTO subunidades VALUES ('07021100', 'SUBDIRECCION GESTION DE PERSONAL');
INSERT INTO subunidades VALUES ('1B140101', 'DPTO. DIDACTICA GENERAL Y DIDACTICAS ESP');
INSERT INTO subunidades VALUES ('02250300', 'PROTOCOLO E IMAGEN');
INSERT INTO subunidades VALUES ('02250400', 'SEGUIMIENTO DE CONVENIOS INSTITUCIONALES');
INSERT INTO subunidades VALUES ('02250500', 'RELACIONES INSTITUCIONALES');
INSERT INTO subunidades VALUES ('02500001', 'SEC. ADM. VICERR.TECN. E INNOVACION EDUC');
INSERT INTO subunidades VALUES ('02300001', 'SEC. ADM. VICERR.REL. INTERNACIONALES Y');
INSERT INTO subunidades VALUES ('02250001', 'SEC. ADM. VICERR.REL. INSTITUCIONALES');
INSERT INTO subunidades VALUES ('07021103', 'PLANIFICACION DOCENTE');
INSERT INTO subunidades VALUES ('06011001', 'SEC. ADM. JEFATURA AREA RR.HH.');
INSERT INTO subunidades VALUES ('07041400', 'SUBDIRECCION DE PRESUPUESTOS');
INSERT INTO subunidades VALUES ('07081200', 'SUBDIRECCION FORMACION E INTERNACIONALIZ');
INSERT INTO subunidades VALUES ('07081201', 'FORMACION E INTERNACIONALIZACION DEL PAS');
INSERT INTO subunidades VALUES ('07051240', 'VERIFICACION DE ESPACIOS Y ALQUILERES');
INSERT INTO subunidades VALUES ('07051250', 'GESTION DE ESPACIOS');
INSERT INTO subunidades VALUES ('07031202', 'PAGOS Y CONTROL DE CUENTAS');
INSERT INTO subunidades VALUES ('07020000', 'SERVICIO GESTION DE PERSONAL');
INSERT INTO subunidades VALUES ('02650001', 'SEC. ADM. VICERR. INFRAEST. ESPAC. Y MED');
INSERT INTO subunidades VALUES ('02651100', 'OFICINA ECOCAMPUS');
INSERT INTO subunidades VALUES ('06011000', 'JEFATURA AREA DE RECURSOS HUMANOS');
INSERT INTO subunidades VALUES ('07130311', 'PROY. PUBLICOS DE INVESTIGACION Y BECAS');

end;
